version: '3'
services:
  flask:
    container_name: flask
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - FLASK_DEBUG='${FLASK_DEBUG:-0}'
      ## Позволяет отслеживать процесс работы приложения в командной строке
      - PYTHONUNBUFFERED='${PYTHONUNBUFFERED:-False}'
    # restart: on-failure
    volumes:
      - .:/app
    networks:
      - ingredients_sail
    # Открываем порт в контейнер
    # Порт, который будет смотреть наружу : порт который используется внутри контейнера
    ports:
      - "8000:8000"
    command: flask run
networks:
  ingredients_sail:
    external: true
